hello/urls.py
from django.urls import path

from hello import views

urlpatterns = [
    path('home/', views.hello_view),
    path('home2/', views.hello2_view),
    path('adam/', views.adam_view),
    path('ewa/', views.ewa_view),
    # path('<str:name>/', views.name_view),  # Konwerter scieżki
    path('<str:name>/', views.name_view2),
]

inheritance/urls.py
from django.urls import path

from inheritance import views

app_name = 'inheritance'

urlpatterns = [
    path('first/', views.first, name='first'),
    path('second/', views.second, name='second'),
]

intro/intro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from intro import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('hello.urls')),
]

intro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('isitchristmas/', include('isitchristmas.urls')),
    path('fruits/', include('fruits.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form_app/', include('form_app.urls')),
    path('form_app2/', include('form_app2.urls')),
    path('form_app3/', include('form_app3.urls')),
    path('form_app4/', include('form_app4.urls')),
    path('form_app5/', include('form_app5.urls')),
    path('form_app6/', include('form_app6.urls')),
    path('form_app7/', include('form_app7.urls')),
    path('relations/', include('relations.urls')),
    path('formapp/', include('formapp.urls')),
    path('viewapp/', include('viewapp.urls')),
    path('auth/', include('auth_user.urls')),
    path('uwierzytelnienie/', include('uwierzytelnienie.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

inheritance/views.py
from django.shortcuts import render


def first(request):
    return render(
        request,
        'inheritance/first.html'
    )


def second(request):
    return render(
        request,
        'inheritance/second.html'
    )

inheritance/templates/inheritance/first.html
{% extends 'inheritance/layout.html' %}

{% block title %}
    Pierwsze
{% endblock %}

{% block body %}
    <div class="container">
        <div class="alert alert-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet consectetur consequatur ea ex excepturi in ipsa ipsam minus, mollitia obcaecati officia quas repudiandae sequi sit soluta tempora voluptas voluptatibus</div>

        <p>Przejdź do strony <a href="{% url 'inheritance:second' %}">drugiej</a></p>
    </div>
{% endblock %}

inheritance/templates/inheritance/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- CDN -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->

    <!-- Albo pobieramy klasy bootstrapowe i umieszczamy na serwerze django w pliku static/inheritance/style.css -->
    <link rel="stylesheet" href="{% static 'inheritance/style.css' %}">
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

inheritance/templates/inheritance/second.html
{% extends 'inheritance/layout.html' %}

{% block title %}
Drugi
{% endblock %}

{% block body %}
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum nihil possimus quos rem reprehenderit similique voluptates voluptatum. Aspernatur atque corporis, cumque error minus molestiae nesciunt obcaecati possimus quae, reprehenderit vero?
<p>Przejdź do strony <a href="{% url 'inheritance:first' %}">pierwszej</a></p>
{% endblock %}