form_app5/urls.py
from django.urls import path

from form_app5 import views

app_name = 'form_app5'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('tasks-list/', views.tasks_list, name='tasks-list'),
]

hello/urls.py
from django.urls import path

from hello import views

urlpatterns = [
    path('home/', views.hello_view),
    path('home2/', views.hello2_view),
    path('adam/', views.adam_view),
    path('ewa/', views.ewa_view),
    # path('<str:name>/', views.name_view),  # Konwerter scieżki
    path('<str:name>/', views.name_view2),
]

intro/intro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from intro import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('hello.urls')),
]

intro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('isitchristmas/', include('isitchristmas.urls')),
    path('fruits/', include('fruits.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form_app/', include('form_app.urls')),
    path('form_app2/', include('form_app2.urls')),
    path('form_app3/', include('form_app3.urls')),
    path('form_app4/', include('form_app4.urls')),
    path('form_app5/', include('form_app5.urls')),
    path('form_app6/', include('form_app6.urls')),
    path('form_app7/', include('form_app7.urls')),
    path('relations/', include('relations.urls')),
    path('formapp/', include('formapp.urls')),
    path('viewapp/', include('viewapp.urls')),
    path('auth/', include('auth_user.urls')),
    path('uwierzytelnienie/', include('uwierzytelnienie.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

form_app5/models.py
from django.db import models


class Task(models.Model):
    text = models.TextField()

    def __str__(self):
        return f"{self.text}"

form_app5/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from form_app5.models import Task


def register(request):
    return render(
        request,
        'form_app5/register.html',
    )


def tasks_list(request):

    task = request.POST.get('task')

    with open('tasks.txt', 'a+') as f:
        if task:
            # Create
            Task.objects.create(text=task)
            return redirect('form_app5:tasks-list')

    # Read
    tasks = Task.objects.all()

    return render(
        request,
        'form_app5/tasks-list.html',
        context={
            'tasks': tasks,
        }
    )

form_app5/templates/form_app5/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zarejestruj zadanie</title>
</head>
<body>
    <form action="{% url 'form_app5:tasks-list' %}" method="post">
        {% csrf_token %}
        <input type="text" name="task">
        <input type="submit" value="Zarejestruj">
    </form>
</body>
</html>

form_app5/templates/form_app5/tasks-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'form_app5:register' %}"><button>Zarejestruj</button></a>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
</body>
</html>